FPAttributeValueFile

n SubType="IVI"

n SubVersion="1"

v attrAcqTriggeredSlopeRangeTable DataType="i"
 AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_POS (1)
  "Specifies a rising slope of the output signal."

 AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_NEG (2)
  "specifies a falling slope of the output signal."


v attrArbWfmTypeRangeTable DataType="i"
 AGN6K7KNI_VAL_ARB_WFM_TYPE_VOLT (1)
  "Specifies a voltage Arb"

 AGN6K7KNI_VAL_ARB_WFM_TYPE_CURR (2)
  "Specifies a current Arb"


v attrCalibrationLevelRangeTable DataType="i"
 AGN6K7KNI_VAL_CAL_LEVEL_P1 (1)
  "Advances to the first level in the calibration."

 AGN6K7KNI_VAL_CAL_LEVEL_P2 (2)
  "Advances to the second level in the calibration."

 AGN6K7KNI_VAL_CAL_LEVEL_P3 (3)
  "Advances to the third level in the calibration."


v attrDigitalInhibitModeRangeTable DataType="i"
 AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_LATCHING (1)
  "A logic-true signal on the Inhibit input causes the output state to latch "
  "OFF."

 AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_LIVE (2)
  "Allows the enabled output to follow the state of the Inhibit input."

 AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_OFF (3)
  "The Inhibit input is ignored."


v attrDigitalPinFunctionRangeTable DataType="i"
 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_DIO (1)
  "General-purpose ground-referenced digital input/output function."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_DIN (2)
  "Digital input-only mode."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR1 (3)
  "User-defined expression 1 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR2 (4)
  "User-defined expression 2 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR3 (5)
  "User-defined expression 3 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR4 (6)
  "User-defined expression 4 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR5 (7)
  "User-defined expression 5 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR6 (8)
  "User-defined expression 6 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR7 (9)
  "User-defined expression 7 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR8 (10)
  "User-defined expression 8 drives the pin."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_FAULT (11)
  "Pin 1 functions as an isolated fault output."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_INHIBIT (12)
  "Pin 3 functions as an inhibit input."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_ON_COUPLE (13)
  "Pins 4 -7 synchronize the output On state."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_OFF_COUPLE (14)
  "Pins 4 -7 synchronize the output Off state."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_TRIG_INPUT (15)
  "A trigger input function."

 AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_TRIG_OUTPUT (16)
  "A trigger output function"


v attrDigitalPinPolarityRangeTable DataType="i"
 AGN6K7KNI_VAL_DIGITAL_PIN_POL_POS (1)
  "A logical true signal is a voltage high at the pin"

 AGN6K7KNI_VAL_DIGITAL_PIN_POL_NEG (2)
  "A logical true signal is a voltage low at the pin"


v attrExpressionSourceRangeTable DataType="i"
 AGN6K7KNI_VAL_EXPRESSION_SOURCE_NONE (0)
  "No expression source"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR1 (1)
  "User-defined expression 1"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR2 (2)
  "User-defined expression 2"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR3 (3)
  "User-defined expression 3"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR4 (4)
  "User-defined expression 4"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR5 (5)
  "User-defined expression 5"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR6 (6)
  "User-defined expression 6"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR7 (7)
  "User-defined expression 7"

 AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR8 (8)
  "User-defined expression 8"


v attrFunctionRangeTable DataType="i"
 AGN6K7KNI_VAL_FUNCTION_VOLTAGE (1)
  "Voltage priority"

 AGN6K7KNI_VAL_FUNCTION_CURRENT (2)
  "Current priority"


v attrListStepRangeTable DataType="i"
 AGN6K7KNI_VAL_LIST_STEP_AUTO (1)
  "Dwell Paced"

 AGN6K7KNI_VAL_LIST_STEP_ONCE (2)
  "Trigger Paced"


v attrMeasurementTypeRangeTable DataType="i"
 AGN6K7KNI_VAL_MEAS_TYPE_CURRENT_DC (0)
  "Average Current (DC)"

 AGN6K7KNI_VAL_MEAS_TYPE_CURRENT_RMS (1000)
  "RMS current (AC + DC)"

 AGN6K7KNI_VAL_MEAS_TYPE_CURRENT_HIGH (1001)
  "High Level Of Current Pulse"

 AGN6K7KNI_VAL_MEAS_TYPE_CURRENT_LOW (1002)
  "Low Level Of Current Pulse"

 AGN6K7KNI_VAL_MEAS_TYPE_CURRENT_MAX (1003)
  "Maximum Current"

 AGN6K7KNI_VAL_MEAS_TYPE_CURRENT_MIN (1004)
  "Minimum Current"

 AGN6K7KNI_VAL_MEAS_TYPE_VOLTAGE_DC (1)
  "Average Voltage (DC)"

 AGN6K7KNI_VAL_MEAS_TYPE_VOLTAGE_RMS (1005)
  "RMS Voltage (AC + DC)"

 AGN6K7KNI_VAL_MEAS_TYPE_VOLTAGE_HIGH (1006)
  "High Level Of Voltage Pulse"

 AGN6K7KNI_VAL_MEAS_TYPE_VOLTAGE_LOW (1007)
  "Low Level Of Voltage Pulse"

 AGN6K7KNI_VAL_MEAS_TYPE_VOLTAGE_MAX (1008)
  "Maximum Voltage"

 AGN6K7KNI_VAL_MEAS_TYPE_VOLTAGE_MIN (1009)
  "Minimum Voltage"

 AGN6K7KNI_VAL_MEAS_TYPE_POWER_DC (1010)
  "Average Power"

 AGN6K7KNI_VAL_MEAS_TYPE_AHO (1011)
  "Amp-hour"

 AGN6K7KNI_VAL_MEAS_TYPE_WHO (1012)
  "Watt-hour"


v attrMeasurementWindowRangeTable DataType="i"
 AGN6K7KNI_VAL_MEAS_WINDOW_HANNING (1)
  "Hanning window"

 AGN6K7KNI_VAL_MEAS_WINDOW_RECT (2)
  "Rectangular window"


v attrOcpDelayStartTimeRangeTable DataType="i"
 AGN6K7KNI_VAL_OCP_DELAY_START_SCHANGE (1)
  "Settings Change"

 AGN6K7KNI_VAL_OCP_DELAY_START_CCTRANS (2)
  "CC Transition"


v attrOutputRelayPolarityRangeTable DataType="i"
 AGN6K7KNI_VAL_RELAY_POLARITY_NORMAL (1)
  "Normal"

 AGN6K7KNI_VAL_RELAY_POLARITY_REVERSE (2)
  "Reverse"


v attrThresholdComparatorNumberRangeTable DataType="i"
 AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_1 (1)
  "Comparator 1"

 AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_2 (2)
  "Comparator 2"

 AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_3 (3)
  "Comparator 3"

 AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_4 (4)
  "Comparator 4"


v attrThresholdFunctionRangeTable DataType="i"
 AGN6K7KNI_VAL_THRESHOLD_FUNC_AHOUR (1)
  "Ampere-hour"

 AGN6K7KNI_VAL_THRESHOLD_FUNC_CURRENT (2)
  "Current"

 AGN6K7KNI_VAL_THRESHOLD_FUNC_POWER (3)
  "Power"

 AGN6K7KNI_VAL_THRESHOLD_FUNC_VOLTAGE (4)
  "Voltage"

 AGN6K7KNI_VAL_THRESHOLD_FUNC_WHOUR (5)
  "Watt-hour"


v attrThresholdOperationRangeTable DataType="i"
 AGN6K7KNI_VAL_THRESHOLD_OPERATION_GT (1)
  "Greater Than"

 AGN6K7KNI_VAL_THRESHOLD_OPERATION_LT (2)
  "Less Than"


v attrTransientModeRangeTable DataType="i"
 AGN6K7KNI_VAL_TRANSIENT_MODE_FIXED (1)
  "Keeps the output voltage at its immediate value."

 AGN6K7KNI_VAL_TRANSIENT_MODE_STEP (2)
  "Steps the output to the triggered level when a trigger occurs."

 AGN6K7KNI_VAL_TRANSIENT_MODE_LIST (3)
  "Causes the output to follow the list values when a trigger occurs."

 AGN6K7KNI_VAL_TRANSIENT_MODE_ARB (4)
  "Causes the output to follow the arbitrary waveform values when a trigger "
  "occurs."


v attrTriggerSourceRangeTable DataType="i"
 AGN6K7KNI_VAL_SOFTWARE_TRIG (2)
  "The power supply waits for you to call the agn6k7kni_SendSoftwareTrigger "
  "function."

 AGN6K7KNI_VAL_TRIG_EXTERNAL (1)
  "The power supply waits for a trigger on the external trigger input."

 AGN6K7KNI_VAL_TRIG_IMMEDIATE (0)
  "The power supply does not wait for a trigger before changing the output "
  "signal."

 AGN6K7KNI_VAL_TRIG_EXPR1 (1000)
  "Selects user-defined expression 1 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR2 (1001)
  "Selects user-defined expression 2 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR3 (1002)
  "Selects user-defined expression 3 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR4 (1003)
  "Selects user-defined expression 4 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR5 (1004)
  "Selects user-defined expression 5 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR6 (1005)
  "Selects user-defined expression 6 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR7 (1006)
  "Selects user-defined expression 7 as the trigger source."

 AGN6K7KNI_VAL_TRIG_EXPR8 (1007)
  "Selects user-defined expression 8 as the trigger source."

 AGN6K7KNI_VAL_TRIG_PIN1 (1008)
  "Selects digital port pin 1 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_PIN2 (1009)
  "Selects digital port pin 2 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_PIN3 (1010)
  "Selects digital port pin 3 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_PIN4 (1011)
  "Selects digital port pin 4 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_PIN5 (1012)
  "Selects digital port pin 5 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_PIN6 (1013)
  "Selects digital port pin 6 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_PIN7 (1014)
  "Selects digital port pin 7 configured as a trigger input."

 AGN6K7KNI_VAL_TRIG_CURRENT (1015)
  "Selects an output current level"

 AGN6K7KNI_VAL_TRIG_TRANSIENT (1016)
  "Selects the transient system as the trigger source"

 AGN6K7KNI_VAL_TRIG_VOLTAGE (1017)
  "Selects an output voltage level"


v attrVoltageBandwidthRangeTable DataType="i"
 AGN6K7KNI_VAL_VOLTAGE_BANDWIDTH_HIGH (1)
  "Provides maximum up-programming speed as well as the fastest transient "
  "response time when the output capacitance is restricted to small values."

 AGN6K7KNI_VAL_VOLTAGE_BANDWIDTH_LOW (2)
  "Optimized for use with large capacitive loads"


v calibrationModeRangeTable DataType="i"
 AGN6K7KNI_VAL_CAL_MODE_VOLTAGE (1)
  "Calibrates the voltage level"

 AGN6K7KNI_VAL_CAL_MODE_CMRR (2)
  "Calibrates the voltage common mode rejection ratio"

 AGN6K7KNI_VAL_CAL_MODE_TC (3)
  "Calibrates the temperature coefficient"

 AGN6K7KNI_VAL_CAL_MODE_CURRENT_HIGH_RANGE (4)
  "Calibrates the high current level"

 AGN6K7KNI_VAL_CAL_MODE_CURRENT_LOW_RANGE (5)
  "Calibrates the low current level"

 AGN6K7KNI_VAL_CAL_MODE_CURRENT_SHARING (6)
  "Calibrates the current sharing"

 AGN6K7KNI_VAL_CAL_MODE_BOTTOM_OUT_RES (7)
  "Calibrates the bottom out resistance"


v outputStateRangeTable DataType="i"
 AGN6K7KNI_VAL_OUTPUT_CONSTANT_VOLTAGE (0)
  "Output is in constant voltage"

 AGN6K7KNI_VAL_OUTPUT_CONSTANT_CURRENT (1)
  "Output is in constant current"

 AGN6K7KNI_VAL_OUTPUT_UNREGULATED (4)
  "Output is unregulated"

 AGN6K7KNI_VAL_OUTPUT_OVER_VOLTAGE (2)
  "Output is disabled by the over-voltage protection"

 AGN6K7KNI_VAL_OUTPUT_OVER_VOLTAGE_NEGATIVE (1000)
  "Output is disabled by a negative OV due to reversed sense leads"

 AGN6K7KNI_VAL_OUTPUT_OVER_CURRENT (3)
  "Output is disabled by the over-current protection"

 AGN6K7KNI_VAL_OUTPUT_OVER_POWER (1001)
  "Output is disabled by the positive over-power limit"

 AGN6K7KNI_VAL_OUTPUT_OVER_POWER_NEGATIVE (1002)
  "Output is disabled by the negative over-power limit"

 AGN6K7KNI_VAL_OUTPUT_OVER_TEMPERATURE (1003)
  "Output is disabled by the over-temperature protection"


v Boolean_values DataType="i"
 VI_TRUE (1)
  "True"

 VI_FALSE (0)
  "False"


v attrCurrentLimitBehaviorRangeTable DataType="i"
 AGN6K7KNI_VAL_CURRENT_REGULATE (0)
  "When the output current reaches the value of the "
  "AGN6K7KNI_ATTR_CURRENT_LIMIT attribute, the power supply restricts the "
  "output voltage such that the output current is not greater than the value "
  "of the AGN6K7KNI_ATTR_CURRENT_LIMIT attribute."

 AGN6K7KNI_VAL_CURRENT_TRIP (1)
  "When the output current reaches or exceeds the value of the "
  "AGN6K7KNI_ATTR_CURRENT_LIMIT attribute, the power supply disables the "
  "output."


0 agn6k7kni_SetAttributeViInt32 3 4 false s DataType="ViInt32"
0 agn6k7kni_GetAttributeViInt32 3 4 false g DataType="ViInt32"
0 agn6k7kni_CheckAttributeViInt32 3 4 false s DataType="ViInt32"
0 agn6k7kni_SetAttributeViInt64 3 4 false s DataType="ViInt64"
0 agn6k7kni_GetAttributeViInt64 3 4 false g DataType="ViInt64"
0 agn6k7kni_CheckAttributeViInt64 3 4 false s DataType="ViInt64"
0 agn6k7kni_SetAttributeViReal64 3 4 false s DataType="ViReal64"
0 agn6k7kni_GetAttributeViReal64 3 4 false g DataType="ViReal64"
0 agn6k7kni_CheckAttributeViReal64 3 4 false s DataType="ViReal64"
0 agn6k7kni_SetAttributeViSession 3 4 false s DataType="ViSession"
0 agn6k7kni_GetAttributeViSession 3 4 false g DataType="ViSession"
0 agn6k7kni_CheckAttributeViSession 3 4 false s DataType="ViSession"
0 agn6k7kni_SetAttributeViBoolean 3 4 false s DataType="ViBoolean"
0 agn6k7kni_GetAttributeViBoolean 3 5 false g DataType="ViBoolean"
0 agn6k7kni_CheckAttributeViBoolean 3 4 false s DataType="ViBoolean"
0 agn6k7kni_SetAttributeViString 3 4 false s DataType="ViString"
0 agn6k7kni_GetAttributeViString 3 4 false g DataType="ViString"
0 agn6k7kni_CheckAttributeViString 3 4 false s DataType="ViString"

1 all "Inherent IVI Attributes"
  "Attributes common to all IVI instrument drivers."

2 all "User Options"
  "Attributes you can set to affect the operation of this instrument driver.\n"
  "    "

3 all "Range Check" AGN6K7KNI_ATTR_RANGE_CHECK ViBoolean gs Boolean_values
  "Specifies whether to validate attribute values and function parameters.  "
  "If enabled, the instrument driver validates the parameter values that you "
  "pass to driver functions.  Range checking parameters is very useful for "
  "debugging.  After you validate your program, you can set this attribute to "
  "VI_FALSE to disable range checking and maximize performance.\n"
  "    The default value is VI_TRUE.  Use the agn6k7kni_InitWithOptions "
  "function to override this value.\n"
  "\n"
  "Attribute Value: 1050002"

3 all "Query Instrument Status" AGN6K7KNI_ATTR_QUERY_INSTRUMENT_STATUS ViBoolean gs Boolean_values
  "Specifies whether the instrument driver queries the instrument status "
  "after each operation.  Querying the instrument status is very useful for "
  "debugging.  After you validate your program, you can set this attribute to "
  "VI_FALSE to disable status checking and maximize performance\n"
  "    The instrument driver can choose to ignore status checking for "
  "particular attributes regardless of the setting of this attribute.\n"
  "    The default value is VI_FALSE.  Use the agn6k7kni_InitWithOptions "
  "function to override this value.\n"
  "\n"
  "Attribute Value: 1050003"

3 all "Cache" AGN6K7KNI_ATTR_CACHE ViBoolean gs Boolean_values
  "Specifies whether to cache the value of attributes.  When caching is "
  "enabled, the instrument driver keeps track of the current instrument "
  "settings and avoids sending redundant commands to the instrument.  Thus, "
  "you can significantly increase execution speed.\n"
  "    The instrument driver can choose always to cache or never to cache "
  "particular attributes regardless of the setting of this attribute.\n"
  "    The default value is VI_TRUE.  Use the agn6k7kni_InitWithOptions "
  "function to override this value.\n"
  "\n"
  "Attribute Value: 1050004"

3 all "Simulate" AGN6K7KNI_ATTR_SIMULATE ViBoolean gs Boolean_values
  "Specifies whether or not to simulate instrument driver I/O operations.  "
  "If simulation is enabled, instrument driver functions perform range "
  "checking and call Ivi_GetAttribute and Ivi_SetAttribute functions, but "
  "they do not perform instrument I/O.  For output parameters that represent "
  "instrument data, the instrument driver functions return calculated values.\n"
  "    The default value is VI_FALSE.  Use the agn6k7kni_InitWithOptions "
  "function to override this value.\n"
  "\n"
  "Attribute Value: 1050005"

3 all "Record Value Coercions" AGN6K7KNI_ATTR_RECORD_COERCIONS ViBoolean gs Boolean_values
  "Specifies whether the IVI engine keeps a list of the value coercions it "
  "makes for integer and real type attributes.  You call agn6k7kni Get Next "
  "Coercion Record to extract and delete the oldest coercion record from the "
  "list.\n"
  "    The default value is VI_FALSE.  Use the agn6k7kni_InitWithOptions "
  "function to override this value.\n"
  "\n"
  "Attribute Value: 1050006"

3 all "Interchange Check" AGN6K7KNI_ATTR_INTERCHANGE_CHECK ViBoolean gs Boolean_values
  "Specifies whether to perform interchangeability checking and retrieve "
  "interchangeability warnings.\n"
  "\n"
  "The default value is VI_FALSE.\n"
  "\n"
  "Interchangeability warnings indicate that using your application with a "
  "different instrument might cause different behavior.  You call agn6k7kni "
  "Get Next Interchange Warning to extract interchange warnings.  Call the "
  "agn6k7kni_ClearInterchangeWarnings function to clear the list of "
  "interchangeability warnings without reading them.\n"
  "Interchangeability checking logs a warning for each attribute you have not "
  "set that affects the behavior of the instrument.\n"
  "\n"
  "Attribute Value: 1050021"

2 all "Driver Identification"
  "Attributes that provide identity and version information about this "
  "instrument driver.\n"
  "    "

3 all "Description" AGN6K7KNI_ATTR_SPECIFIC_DRIVER_DESCRIPTION ViString g
  "A string that contains a brief description of the specific driver.\n"
  "\n"
  "Attribute Value: 1050514"

3 all "Driver Prefix" AGN6K7KNI_ATTR_SPECIFIC_DRIVER_PREFIX ViString g
  "A string that contains the prefix for the instrument driver.  The name of "
  "each user-callable function in this driver starts with this prefix.\n"
  "\n"
  "Attribute Value: 1050302"

3 all "Driver Vendor" AGN6K7KNI_ATTR_SPECIFIC_DRIVER_VENDOR ViString g
  "A string that contains the name of the vendor that supplies this driver.\n"
  "\n"
  "Attribute Value: 1050513"

3 all "Revision" AGN6K7KNI_ATTR_SPECIFIC_DRIVER_REVISION ViString g
  "A string that contains additional version information about this "
  "instrument driver.\n"
  "\n"
  "Attribute Value: 1050551"

3 all "Class Specification Major Version" AGN6K7KNI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MAJOR_VERSION ViInt32 g
  "The major version number of the class specification with which this "
  "driver is compliant.\n"
  "\n"
  "Attribute Value: 1050515"

3 all "Class Specification Minor Version" AGN6K7KNI_ATTR_SPECIFIC_DRIVER_CLASS_SPEC_MINOR_VERSION ViInt32 g
  "The minor version number of the class specification with which this "
  "driver is compliant.\n"
  "\n"
  "Attribute Value: 1050516"

2 all "Driver Capabilities"
  "Attributes that provide information about the capabilities of this "
  "instrument driver.\n"
  "    "

3 all "Supported Instrument Models" AGN6K7KNI_ATTR_SUPPORTED_INSTRUMENT_MODELS ViString g
  "Contains a model code of the instrument. For drivers that support more "
  "than one device, this attribute contains a comma-separated list of "
  "supported instrument models.\n"
  "\n"
  "Attribute Value: 1050327"

3 all "Class Group Capabilities" AGN6K7KNI_ATTR_GROUP_CAPABILITIES ViString g
  "A string that contains a comma-separated list of class-extension groups "
  "that this driver implements.\n"
  "\n"
  "Attribute Value: 1050401"

2 all "Instrument Identification"
  "Attributes that provide identity information about the instrument that "
  "you are using.    "

3 all "Manufacturer" AGN6K7KNI_ATTR_INSTRUMENT_MANUFACTURER ViString g
  "A string that contains the name of the instrument manufacturer you are "
  "currently using.\n"
  "\n"
  "Attribute Value: 1050511"

3 all "Model" AGN6K7KNI_ATTR_INSTRUMENT_MODEL ViString g
  "A string that contains the model number or name of the instrument that "
  "you are currently using.\n"
  "\n"
  "Attribute Value: 1050512"

3 all "Firmware Revision" AGN6K7KNI_ATTR_INSTRUMENT_FIRMWARE_REVISION ViString g
  "A string that contains the firmware revision information for the "
  "instrument you are currently using.\n"
  "\n"
  "Attribute Value: 1050510"

2 all "Advanced Session Information"
  "Attributes that contain additional information concerning the instrument "
  "driver session.      "

3 all "Logical Name" AGN6K7KNI_ATTR_LOGICAL_NAME ViString g
  "A string containing the logical name you specified when opening the "
  "current IVI session.\n"
  "     You may pass a logical name to the agn6k7kni_init or "
  "agn6k7kni_InitWithOptions functions.  The IVI Configuration utility must "
  "contain an entry for the logical name.  The logical name entry refers to a "
  "virtual instrument section in the IVI Configuration file.  The virtual "
  "instrument section specifies a physical device and initial user options.\n"
  "\n"
  "Attribute Value: 1050305"

3 all "I/O Resource Descriptor" AGN6K7KNI_ATTR_IO_RESOURCE_DESCRIPTOR ViString g
  "Indicates the resource descriptor the driver uses to identify the "
  "physical device.\n"
  "    If you initialize the driver with a logical name, this attribute "
  "contains the resource descriptor that corresponds to the entry in the IVI "
  "Configuration utility.  \n"
  "    If you initialize the instrument driver with the resource descriptor, "
  "this attribute contains that value.\n"
  "\n"
  "Attribute Value: 1050304"

3 all "Driver Setup" AGN6K7KNI_ATTR_DRIVER_SETUP ViString g
  "Some cases exist where you must specify instrument driver options at "
  "initialization time.  An example of this is specifying a particular "
  "instrument model from among a family of instruments that the driver "
  "supports.  This is useful when using simulation.  You can specify "
  "driver-specific options through the DriverSetup keyword in the "
  "optionsString parameter to the agn6k7kni_InitWithOptions function.  If you "
  "open an instrument using a logical name, you can also specify the options "
  "through the IVI Configuration Utility.\n"
  "    The default value is an empty string.\n"
  "\n"
  "Attribute Value: 1050007"

1 all "Basic Operation"
  "Attributes for controlling the basic features of the DC power supply."

2 all "Current Level" AGN6K7KNI_ATTR_CURRENT_LEVEL ViReal64 gs
  "This channel-based attribute sets the current level when the output is "
  "operating in current priority mode.\n"
  "\n"
  "Valid Range:\n"
  "-10.2% to 102% of rating without power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -10.2 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: -5.1 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: -2.55 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6956A and N7956A: -1.7 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6957A and N7957A: -1.275 to 12.75 A\n"
  "\n"
  "\n"
  "up to -102% to 102% of rating with power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -102 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: -51 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: -25.5 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6956A and N7956A: -17 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6957A and N7957A: -12.75 to 12.75 A\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 1.02 A\n"
  "N6951A, N6971A, N7951A and N7971A: 0.51 A\n"
  "N6952A, N6972A, N7952A and N7972A: 0.255 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6956A and N7956A: 0.17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6957A and N7957A: 0.1275 A\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent[:LEVel][:IMMediate][:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1151018"

2 all "Positive Current Limit" AGN6K7KNI_ATTR_CURRENT_LIMIT ViReal64 gs
  "This channel-based attribute positive current limit when in voltage "
  "priority mode.  Units are in amperes.  The maximum value depends on the "
  "current rating of the unit. \n"
  "\n"
  "Valid Range:\n"
  "0 to 102% of rating. If current rating is 100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: 0 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: 0 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: 0 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: 0 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: 0 to 12.75 A\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 1.02 A\n"
  "N6951A, N6971A, N7951A and N7971A: 0.51A\n"
  "N6952A, N6972A, N7952A and N7972A: 0.255 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: 0.17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: 0.1275 A\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:LIMit[:POSitive][:IMMediate][:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1250005"

2 all "Current Limit Behavior" AGN6K7KNI_ATTR_CURRENT_LIMIT_BEHAVIOR ViInt32 gs
  "This channel-based attribute is not supported.\n"
  "\n"
  "This channel-based attribute specifies the behavior of the power supply "
  "when the output current is equal to or greater than the value of the "
  "AGN6K7KNI_ATTR_CURRENT_LIMIT attribute.\n"
  "\n"
  "Attribute Value: 1250004"

2 all "Negative Current Limit" AGN6K7KNI_ATTR_CURRENT_LIMIT_NEGATIVE ViReal64 gs
  "This channel-based attribute sets the negative current limit when in "
  "voltage priority mode.  Units are in amperes.  The minimum value is the "
  "most negative value.\n"
  "\n"
  "Valid Range:\n"
  "-10.2% of rating to 0 without power dissipator, If current rating is 100%, "
  "then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -10.2 to 0 A\n"
  "N6951A, N6971A, N7951A and N7971A: -5.1 to 0 A\n"
  "N6952A, N6972A, N7952A and N7972A: -2.55 to 0 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -1.7 to 0 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -1.275 to 0 A\n"
  "\n"
  "up to -102% of rating to 0 with power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -102 to 0 A\n"
  "N6951A, N6971A, N7951A and N7971A: -51 to 0 A\n"
  "N6952A, N6972A, N7952A and N7972A: -25.5 to 0 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -17 to 0 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -12.75 to 0 A\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: -10.2 A\n"
  "N6951A, N6971A, N7951A and N7971A: -5.1 A\n"
  "N6952A, N6972A, N7952A and N7972A: -2.55 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -1.7 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -1.275 A\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:LIMit:NEGative[:IMMediate][:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1151019"

2 all "Current Sharing Enabled" AGN6K7KNI_ATTR_CURRENT_SHARING_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables current sharing on "
  "paralleled units.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enable, the load current is shared equally among the paralleled "
  "outputs.\n"
  "VI_FALSE - Disable\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:SHARing[:STATe] 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151001"

2 all "Current Slew Rate" AGN6K7KNI_ATTR_CURRENT_SLEW_RATE ViReal64 gs
  "This channel-based attribute sets the current slew rate. The slew rate is "
  "set in amps per second and affects all programmed current changes, "
  "including those due to the output state turning on or off. \n"
  "\n"
  "Valid Range:\n"
  "0 to 9.9E+37\n"
  "\n"
  "Default Value:\n"
  "9.9E+37\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:SLEW[:IMMediate] <value>|MIN|MAX|INFinity\n"
  "\n"
  "Attribute Value: 1151017"

2 all "Max Current Slew Rate Enabled" AGN6K7KNI_ATTR_CURRENT_SLEW_MAX_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the maximum current slew "
  "rate override. \n"
  "\n"
  "Default Value:\n"
  "VI_TRUE - Enables the maximum current slew rate override. \n"
  "VI_FALSE - Disables the maximum current slew rate override. \n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:SLEW:MAXimum 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151002"

2 all "Function" AGN6K7KNI_ATTR_FUNCTION ViInt32 gs attrFunctionRangeTable
  "This channel-based attribute select either Voltage priority or Current "
  "priority. \n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_FUNCTION_VOLTAGE - Voltage priority, the output voltage will "
  "remain at its programmed setting as long as the load current remains "
  "within the positive or negative current limit setting.\n"
  "AGN6K7KNI_VAL_FUNCTION_CURRENT - Current priority,  the output current "
  "will remain at its programmed setting as long as the load voltage remains "
  "within the voltage limit setting.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_FUNCTION_CURRENT\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]FUNCtion CURRent|VOLTage\n"
  "\n"
  "Attribute Value: 1153011"

2 all "OCP Delay" AGN6K7KNI_ATTR_OCP_DELAY ViReal64 gs
  "This channel-based attribute sets the over-current protection delay. The "
  "over-current protection function will not be triggered during the delay "
  "time. After the delay time has expired, the over-current protection "
  "function will be active.\n"
  "\n"
  "Valid Range:\n"
  "0 to 0.255 seconds\n"
  "\n"
  "Default Value:\n"
  "0.020 seconds\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:PROTection:DELay[:TIME] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1151008"

2 all "OCP Delay Start Time" AGN6K7KNI_ATTR_OCP_DELAY_START_TIME ViInt32 gs attrOcpDelayStartTimeRangeTable
  "This channel-based attribute specifies what starts the over-current "
  "protection delay timer.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_OCP_DELAY_START_SCHANGE - Settings Change, starts the "
  "over-current delay whenever a command changes the output settings.\n"
  "AGN6K7KNI_VAL_OCP_DELAY_START_CCTRANS - CC Transition, starts the "
  "over-current delay timer by any transition of the output into current "
  "limit mode.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_OCP_DELAY_START_SCHANGE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:PROTection:DELay:STARt SCHange|CCTRans\n"
  "\n"
  "Attribute Value: 1151007"

2 all "OCP Enabled" AGN6K7KNI_ATTR_OCP_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the over-current "
  "protection.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables over-current protection\n"
  "VI_FALSE - Disables over-current protection\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:PROTection:STATe 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151009"

2 all "Output Couple Enabled" AGN6K7KNI_ATTR_OUTPUT_COUPLE_ENABLED ViBoolean gs Boolean_values
  "This attribute enables or disables output coupling. Output coupling "
  "allows the outputs of multiple instruments to turn on and off sequentially "
  "according to their specified programming delays.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables output coupling\n"
  "VI_FALSE - Disables output coupling\n"
  "\n"
  "Default Value:\n"
  "VI_TRUE\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:COUPle[:STATe] 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1153006"

2 all "Output Delay Fall" AGN6K7KNI_ATTR_OUTPUT_DELAY_FALL ViReal64 gs
  "This channel-based attribute specifies the delay in seconds that the "
  "instrument waits before turning the output off (fall). This allows "
  "multiple instruments to turn off in sequence. The output will not turn off "
  "until its delay time has elapsed.\n"
  "\n"
  "Valid Range:\n"
  "Delay times can be programmed with the following resolution:\n"
  "Range in seconds          Resolution\n"
  "0 to 1.023E-4             100 nanoseconds\n"
  "1.03E-4 to 1.023E-3       1 microsecond\n"
  "1.03E-3 to 1.023E-2       10 microseconds\n"
  "1.03E-2 to 1.023E-1       100 microseconds\n"
  "1.03E-1 to 1.023E+0       1 millisecond\n"
  "1.03E+0 to 1.023E+1       10 milliseconds\n"
  "1.03E+1 to 1.023E+2       100 milliseconds\n"
  "1.03E+2 to 1.023E+3       1 second\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:DELay:FALL <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1153005"

2 all "Output Delay Offset" AGN6K7KNI_ATTR_OUTPUT_DELAY_OFFSET ViReal64 gs
  "This attribute sets a delay offset to synchronize coupled output state "
  "changes.\n"
  "\n"
  "Vaild Range:\n"
  "0 to 1.023\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:COUPle:DOFFset <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1153003"

2 all "Output Delay Rise" AGN6K7KNI_ATTR_OUTPUT_DELAY_RISE ViReal64 gs
  "This channel-based attribute specifies the delay in seconds that the "
  "instrument waits before turning the output on (rise). This allows multiple "
  "instruments to turn on in sequence. The output will not turn on until its "
  "delay time has elapsed.\n"
  "\n"
  "Valid Range:\n"
  "Delay times can be programmed with the following resolution:\n"
  "Range in seconds          Resolution\n"
  "0 to 1.023E-4             100 nanoseconds\n"
  "1.03E-4 to 1.023E-3       1 microsecond\n"
  "1.03E-3 to 1.023E-2       10 microseconds\n"
  "1.03E-2 to 1.023E-1       100 microseconds\n"
  "1.03E-1 to 1.023E+0       1 millisecond\n"
  "1.03E+0 to 1.023E+1       10 milliseconds\n"
  "1.03E+1 to 1.023E+2       100 milliseconds\n"
  "1.03E+2 to 1.023E+3       1 second\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:DELay:RISE <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1153004"

2 all "Output Enabled" AGN6K7KNI_ATTR_OUTPUT_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the output. The state of "
  "a disabled output is a condition of zero output voltage and zero source "
  "current. If output and sense relays are installed, the relays will open "
  "when the output is disabled and close when the output is enabled.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables the output\n"
  "VI_FALSE - Disables the output\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "Notes:\n"
  "(1) Because of internal circuit start-up procedures and any installed "
  "relay options, turn output on may take between 12 and 38 milliseconds to "
  "complete its function in voltage priority mode, and between 14 and 46 "
  "milliseconds in current priority mode.\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:COUPle[:STATe] 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1250006"

2 all "Output Relay Enabled" AGN6K7KNI_ATTR_OUTPUT_RELAY_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the polarity reversal "
  "function.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables output relay polarity\n"
  "VI_FALSE - Disables output relay polarity\n"
  "\n"
  "Default Value:\n"
  "VI_TRUE\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:RELay:POLarity:ENABle 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151012"

2 all "Output Relay Lock Enabled" AGN6K7KNI_ATTR_OUTPUT_RELAY_LOCK_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the polarity reversal "
  "function.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables output relay polarity\n"
  "VI_FALSE - Disables output relay polarity\n"
  "\n"
  "Default Value:\n"
  "VI_TRUE\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:RELay:POLarity:ENABle 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151010"

2 all "Output Relay Polarity" AGN6K7KNI_ATTR_OUTPUT_RELAY_POLARITY ViInt32 gs attrOutputRelayPolarityRangeTable
  "This channel-based attributes sets the polarity of the output relays. "
  "Polarity reversal affects both the output and the sense terminals. \n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_RELAY_POLARITY_NORMAL - Normal, causes the output polarity "
  "to be the same as the output connector labeling.\n"
  "AGN6K7KNI_VAL_RELAY_POLARITY_REVERSE - Reverse, causes the output polarity "
  "to be the reverse of the output connector labeling.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_RELAY_POLARITY_NORMAL\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:RELay:POLarity NORMal|REVerse\n"
  "\n"
  "Attribute Value: 1151011"

2 all "OVP Enabled" AGN6K7KNI_ATTR_OVP_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute specifies whether the power supply provides "
  "over-voltage protection.  If this attribute is set to VI_TRUE, the power "
  "supply disables the output when the output voltage is greater than or "
  "equal to the value of the AGN6K7KNI_ATTR_OVP_LIMIT attribute.\n"
  "\n"
  "Attribute Value: 1250002"

2 all "OVP Limit" AGN6K7KNI_ATTR_OVP_LIMIT ViReal64 gs
  "This channel-based attribute sets the over-voltage protection level.  "
  "Units are in volts. If the output voltage exceeds the OVP level, the "
  "output is disabled and the Questionable Condition status register OV bit "
  "is set.\n"
  "\n"
  "Valid Range:\n"
  "0 to 120% of rating, If current rating is 100%, then the valid range is:\n"
  "N6950A, N6970A, N7950A and N7970A: 0 to 10.8 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0 to 24 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0 to 48 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0 to 72 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0 to 96 V\n"
  "N6976A, N6977A: 0 to 144V\n"
  "N7976A, N7977A: 0 to 192V\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 10.8 V\n"
  "N6951A, N6971A, N7951A and N7971A: 24 V\n"
  "N6952A, N6972A, N7952A and N7972A: 48 V\n"
  "N6953A, N6973A, N7953A and N7973A: 72 V\n"
  "N6954A, N6974A, N7954A and N7974A: 96 V\n"
  "N6976A, N6977A: 144V\n"
  "N7976A, N7977A: 192V\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage:PROTection[:LEVel] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1250003"

2 all "Resistance Enabled" AGN6K7KNI_ATTR_RESISTANCE_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables output resistance "
  "programming.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables output resistance programming.\n"
  "VI_FALSE - Disables output resistance programming.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]RESistance:STATe 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151014"

2 all "Resistance Level" AGN6K7KNI_ATTR_RESISTANCE_LEVEL ViReal64 gs
  "This channel-based attribute sets the output resistance level. Units are "
  "in ohms.\n"
  "\n"
  "Valid Range:\n"
  "N6950A/N7950A: 0 to 0.1 Ohms\n"
  "N6951A/N7951A: 0 to 0.4 Ohms\n"
  "N6952A/N7952A: 0 to 1.6 Ohms\n"
  "N6953A/N7953A: 0 to 3.4 Ohms\n"
  "N6954A/N7954A: 0 to 6.4 Ohms\n"
  "N6970A/N7970A: 0 to 0.05 Ohms\n"
  "N6971A/N7971A: 0 to 0.2 Ohms\n"
  "N6972A/N7972A: 0 to 0.8 Ohms\n"
  "N6973A/N7973A: 0 to 1.7 Ohms\n"
  "N6974A/N7974A: 0 to 3.2 Ohms\n"
  "N6976A/N7976A: 0 to 6.8 Ohms\n"
  "N6977A/N7977A: 0 to 12.8 Ohms\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]RESistance[:LEVel][:IMMediate][:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1151013"

2 all "Voltage Bandwidth" AGN6K7KNI_ATTR_VOLTAGE_BANDWIDTH ViInt32 gs attrVoltageBandwidthRangeTable
  "This channel-based attribute sets the voltage bandwidth. This lets you "
  "optimize output response time with capacitive loads.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_VOLTAGE_BANDWIDTH_HIGH - High Bandwidth,  provides maximum "
  "up-programming speed as well as the fastest transient response time when "
  "the output capacitance is restricted to small values. This mode is "
  "optimized for use with resistive loads; however capacitive loads up to the "
  "limits outlined in the table below can be used when using load leads "
  "shorter than 3 meters (10 feet). Exceeding these limits can lead to "
  "voltage programming overshoots and transient response instability.\n"
  "\n"
  "AGN6K7KNI_VAL_VOLTAGE_BANDWIDTH_LOW - Low Bandwidth, optimized for use "
  "with large capacitive loads up to the limits shown in the table below, "
  "along with load leads longer than 3 meters (10 feet). In this mode the up- "
  "and down-programming speed and voltage control-loop bandwidth are limited "
  "to prevent voltage programming overshoots and improve transient response "
  "stability. Low mode provides the best stability and overshoot minimization "
  "over all load configurations.\n"
  "------------------------------------------------------\n"
  "1 kW Models      High limit        Low limit\n"
  "N6950A/N7950A    0 to 3800 uF      0 to 190,000 uF\n"
  "N6951A/N7951A    0 to 1000 uF      0 to 50,000 uF\n"
  "N6952A/N7952A    0 to 240 uF       0 to 12,000 uF\n"
  "N6953A/N7953A    0 to 100 uF       0 to 5600 uF\n"
  "N6954A/N7954A    0 to 60 uF        0 to 3000 uF\n"
  "------------------------------------------------------\n"
  "2 kW Models      High limit        Low limit\n"
  "N6970A/N7970A    0 to 7600 uF      0 to 380,000 uF      \n"
  "N6971A/N7971A    0 to 2000 uF      0 to 100,000 uF\n"
  "N6972A/N7972A    0 to 480 uF       0 to 24,000 uF\n"
  "N6973A/N7973A    0 to 200 uF       0 to 11,200 uF\n"
  "N6974A/N7974A    0 to 120 uF       0 to 6000 uF\n"
  "N6976A/N7976A    0 to 50 uF        0 to 2,800 uF\n"
  "N6977A/N7977A    0 to 30 uF        0 to 1,500 uF\n"
  "------------------------------------------------------\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_VOLTAGE_BANDWIDTH_HIGH\n"
  "\n"
  "Notes:\n"
  "(1) Connecting very low ESR capacitors larger than the High mode limit "
  "with load leads shorter than 3 m (10 ft.) is not recommended in either "
  "bandwidth range. This load configuration can lead to voltage programming "
  "overshoots.\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage:BWIDth LOW|HIGH1\n"
  "\n"
  "Attribute Value: 1151015"

2 all "Voltage Level" AGN6K7KNI_ATTR_VOLTAGE_LEVEL ViReal64 gs
  "This channel-based attribute sets the voltage level when the output is "
  "operating in voltage priority mode.\n"
  "\n"
  "Valid Range:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 to 9.18 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 to 20.4 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 to 40.8 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 to 61.2 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 to 81.6 V\n"
  "N6976A, N7976A: 0.12 to 122.4 V\n"
  "N6977A, N7977A: 0.16 to 163.2 V\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 V\n"
  "N6976A, N7976A: 0.12 V\n"
  "N6977A, N7977A: 0.16 V\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage[:LEVel][:IMMediate][:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1250001"

2 all "Voltage Limit" AGN6K7KNI_ATTR_VOLTAGE_LIMIT ViReal64 gs
  "This channel-based attribute sets the voltage limit when in current "
  "priority mode.\n"
  "\n"
  "Valid Range:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 to 9.18 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 to 20.4 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 to 40.8 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 to 61.2 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 to 81.6 V\n"
  "N6976A, N7976A: 0.12 to 122.4 V\n"
  "N6977A, N7977A: 0.16 to 163.2 V\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 9.18 V\n"
  "N6951A, N6971A, N7951A and N7971A: 20.4 V\n"
  "N6952A, N6972A, N7952A and N7972A: 40.8 V\n"
  "N6953A, N6973A, N7953A and N7973A: 61.2 V\n"
  "N6954A, N6974A, N7954A and N7974A: 81.6 V\n"
  "N6976A, N7976A: 122.4 V\n"
  "N6977A, N7977A: 163.2 V\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage:LIMit[:POSitive][:IMMediate][:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1151020"

2 all "Max Voltage Slew Rate Enabled" AGN6K7KNI_ATTR_VOLTAGE_SLEW_MAX_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the maximum voltage slew "
  "rate override. \n"
  "\n"
  "Default Value:\n"
  "VI_TRUE - Enables the maximum voltage slew rate override. \n"
  "VI_FALSE - Disables the maximum voltage slew rate override. \n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage:SLEW:MAXimum 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151003"

2 all "Voltage Slew Rate" AGN6K7KNI_ATTR_VOLTAGE_SLEW_RATE ViReal64 gs
  "This channel-based attribute sets the voltage slew rate. The slew rate is "
  "set in volts per second and affects all programmed voltage changes, "
  "including those due to the output state turning on or off.\n"
  "\n"
  "Valid Range:\n"
  "0 to 9.9E+37\n"
  "\n"
  "Default Value:\n"
  "9.9E+37\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage:SLEW[:IMMediate] <value>|MIN|MAX|INFinity\n"
  "\n"
  "Attribute Value: 1151016"

2 all "Watchdog Delay" AGN6K7KNI_ATTR_WATCHDOG_DELAY ViInt32 gs
  "This attribute sets the watchdog delay time.\n"
  "\n"
  "Valid Values:\n"
  "1 to 3600 seconds\n"
  "\n"
  "Default Value:\n"
  "60 seconds\n"
  "\n"
  "Notes\n"
  "(1) When the watchdog timer is enabled, the output is disabled if there is "
  "no SCPI I/O activity on any remote interface (USB, LAN, GPIB) within the "
  "delay time. \n"
  "(2) The watchdog timer function is NOT reset by activity on the front "
  "panel - the output will still shut down after the time period has elapsed.\n"
  "\n"
  "Attribute Value: 1151005"

2 all "Watchdog Timer Enabled" AGN6K7KNI_ATTR_WATCHDOG_TIMER_ENABLED ViBoolean gs Boolean_values
  "This attribute enables or disables the I/O watchdog timer.\n"
  "\n"
  "Valid Value:\n"
  "VI_TRUE - Enables the I/O watchdog timer.\n"
  "VI_FALSE - Disables the I/O watchdog timer.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:PROTection:WDOG[:STATe] 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1151006"

1 all "Trigger Subsystem"
  "Attributes for triggered output changes."

2 all "Current Transient Mode" AGN6K7KNI_ATTR_CURRENT_TRANSIENT_MODE ViInt32 gs attrTransientModeRangeTable
  "This channel-based attribute sets the current transient mode. This "
  "determines what happens to the output voltage when the transient system is "
  "initiated and triggered.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_FIXED - Fixed, keeps the output voltage at "
  "its immediate value.\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_STEP - Step, steps the output to the "
  "triggered level when a trigger occurs.\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_LIST - List, causes the output to follow the "
  "list values when a trigger occurs.\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_ARB - Arbitrary Waveform, causes the output "
  "to follow the arbitrary waveform values when a trigger occurs.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_FIXED\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent:MODE FIXed|STEP|LIST|ARB\n"
  "\n"
  "Attribute Value: 1152009"

2 all "Initiate Continuous" AGN6K7KNI_ATTR_INITIATE_CONTINUOUS ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables continuously initiates "
  "the transient trigger system. This allows multiple triggers to generate "
  "multiple output transients.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables continuous transient trigger\n"
  "VI_FALSE - Disables continuous transient trigger\n"
  "\n"
  "Default Value:\n"
  "VI_TRUE\n"
  "\n"
  "SCPI Command:\n"
  "INITiate:CONTinuous:TRANsient 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1153015"

2 all "Step Trigger Out Enabled" AGN6K7KNI_ATTR_STEP_TRIGGER_OUT_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute specifies whether a trigger out is generated "
  "when a transient step occurs.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE  - Enables trigger out.\n"
  "VI_FALSE - Disables trigger out.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]STEP:TOUTput 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1152001"

2 all "Triggered Current Level" AGN6K7KNI_ATTR_TRIGGERED_CURRENT_LEVEL ViReal64 gs
  "This channel-based attribute sets the triggered current level when the "
  "output is operating in current priority mode.\n"
  "\n"
  "Valid Range:\n"
  "-10.2% to 102% of rating without power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -10.2 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: -5.1 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: -2.55 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -1.7 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -1.275 to 12.75 A\n"
  "\n"
  "\n"
  "up to -102% to 102% of rating with power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -102 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: -51 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: -25.5 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -17 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -12.75 to 12.75 A\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 1.02 A\n"
  "N6951A, N6971A, N7951A and N7971A: 0.51 A\n"
  "N6952A, N6972A, N7952A and N7972A: 0.255 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: 0.17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: 0.1275 A\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]CURRent[:LEVel]:TRIGgered[:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1152010"

2 all "Triggered Current Limit" AGN6K7KNI_ATTR_TRIGGERED_CURRENT_LIMIT ViReal64 gs
  "This channel-based attribute is not supported.\n"
  "\n"
  "SCPI Command:\n"
  "None\n"
  "\n"
  "Attribute Value: 1250102"

2 all "Triggered Voltage Level" AGN6K7KNI_ATTR_TRIGGERED_VOLTAGE_LEVEL ViReal64 gs
  "This channel-based attribute sets the triggered voltage level when the "
  "output is operating in voltage priority mode.\n"
  "\n"
  "Valid Range:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 to 9.18 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 to 20.4 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 to 40.8 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 to 61.2 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 to 81.6 V\n"
  "N6976A, N7976A: 0.12 to 122.4 V\n"
  "N6977A, N7977A: 0.16 to 163.2 V\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 V\n"
  "N6976A, N7976A: 0.12 V\n"
  "N6977A, N7977A: 0.16 V\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage[:LEVel]:TRIGgered[:AMPLitude] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1250103"

2 all "Voltage Transient Mode" AGN6K7KNI_ATTR_VOLTAGE_TRANSIENT_MODE ViInt32 gs attrTransientModeRangeTable
  "This channel-based attribute sets the voltage transient mode. This "
  "determines what happens to the output voltage when the transient system is "
  "initiated and triggered.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_FIXED - Fixed, keeps the output voltage at "
  "its immediate value.\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_STEP - Step, steps the output to the "
  "triggered level when a trigger occurs.\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_LIST - List, causes the output to follow the "
  "list values when a trigger occurs.\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_ARB - Arbitrary Waveform, causes the output "
  "to follow the arbitrary waveform values when a trigger occurs.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_TRANSIENT_MODE_FIXED\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]VOLTage:MODE FIXed|STEP|LIST|ARB\n"
  "\n"
  "Attribute Value: 1152008"

2 all "Trigger Source" AGN6K7KNI_ATTR_TRIGGER_SOURCE ViInt32 gs attrTriggerSourceRangeTable
  "This channel-based attribute selects the trigger source for the transient "
  "system.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_SOFTWARE_TRIG - Software Trigger, Selects a remote interface "
  "trigger command.\n"
  "AGN6K7KNI_VAL_TRIG_EXTERNAL - External, Selects ALL digital port pins that "
  "have been configured as trigger sources.\n"
  "AGN6K7KNI_VAL_TRIG_IMMEDIATE - Immediate, Triggers the transient as soon "
  "as it is initiated.\n"
  "AGN6K7KNI_VAL_TRIG_EXPR<1-8> - Expression1 to Expresstion8, Selects a "
  "user-defined expression as the trigger source.\n"
  "AGN6K7KNI_VAL_TRIG_PIN<1-7> - PIN1 to PIN7, Selects a digital port pin "
  "configured as a trigger input.\n"
  "\n"
  "Default Value: \n"
  "AGN6K7KNI_VAL_SOFTWARE_TRIG\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:TRANsient:SOURce <source>\n"
  "\n"
  "Attribute Value: 1250101"

2 all "List"
  "Attributes for configuring the list settings of the APS. "

3 all "List Count" AGN6K7KNI_ATTR_LIST_COUNT ViInt32 gs
  "This channel-based attribute sets the list repeat count. This sets the "
  "number of times that a list is executed before it completes.\n"
  "\n"
  "Defined Values:\n"
  "AGN6K7KNI_VAL_LIST_COUNT_INFINITY (-1) - Infinity,  runs the list "
  "continuously.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_LIST_COUNT_INFINITY\n"
  "1 to 4096\n"
  "\n"
  "Default Value:\n"
  "1\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]LIST:COUNt <value>|MIN|MAX|INFinity\n"
  "\n"
  "Attribute Value: 1153014"

3 all "List Step" AGN6K7KNI_ATTR_LIST_STEP ViInt32 gs attrListStepRangeTable
  "This channel-based attribute specifies how the list responds to triggers.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_LIST_STEP_AUTO - Dwell Paced, causes the output to "
  "automatically advance to each step, after the receipt of an initial "
  "starting trigger. Steps are paced by the dwell list.\n"
  "AGN6K7KNI_VAL_LIST_STEP_ONCE - Trigger Paced, causes the output to remain "
  "at the present step until a trigger advances it to the next step. Triggers "
  "that arrive during the dwell time are ignored.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_LIST_STEP_AUTO\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]LIST:STEP ONCE|AUTO\n"
  "\n"
  "Attribute Value: 1153013"

3 all "Terminate Last Enabled" AGN6K7KNI_ATTR_LIST_TERMINATE_LAST_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute determines the output value when the list "
  "terminates.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - ON, the output voltage or current remains at the last list step. "
  "The value of the last voltage or current list step becomes the IMMediate "
  "value when the list completes.\n"
  "VI_FALSE - OFF, when the list is aborted, the output returns to the "
  "settings that were in effect before the list started.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]LIST:TERMinate:LAST 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1153012"

2 all "Arbitrary Waveform"
  "Attributes for configuring the arbitrary waveform settings of the APS. "

3 all "Constant Dwell Time" AGN6K7KNI_ATTR_CONSTANT_DWELL_TIME ViReal64 gs
  "This channel-based attribute specifies the dwell time of each point in "
  "the voltage Arb.\n"
  "\n"
  "Valid Range:\n"
  "0.00001024 to 0.30\n"
  "\n"
  "Default Value:\n"
  "0.001\n"
  "\n"
  "Notes:\n"
  "(1) Current and voltage Arbs share settings, so setting this parameter for "
  "a current Arb changes the voltage dwell value and vice versa.\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]ARB:VOLTage:CDWell:DWELl <value>\n"
  "\n"
  "Attribute Value: 1153008"

3 all "Arb Terminate Last Enabled" AGN6K7KNI_ATTR_ARB_TERMINATE_LAST_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute selects the output setting after the Arb "
  "ends.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - ON, the output voltage or current remains at the last Arb value. "
  "The last Arb voltage or current value becomes the IMMediate value when the "
  "ARB completes.\n"
  "VI_FALSE - OFF, the output returns to the settings that were in effect "
  "before the Arb started.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]ARB:TERMinate:LAST 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1153007"

3 all "Arb Trigger Source" AGN6K7KNI_ATTR_ARB_TRIGGER_SOURCE ViInt32 gs attrTriggerSourceRangeTable
  "This channel-based attribute selects the trigger source for arbitrary "
  "waveforms.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_SOFTWARE_TRIG - Software Trigger, Selects a remote interface "
  "trigger command.\n"
  "AGN6K7KNI_VAL_TRIG_EXTERNAL - External, Selects all digital port pins that "
  "have been configured as trigger sources.\n"
  "AGN6K7KNI_VAL_TRIG_IMMEDIATE - Immediate, Triggers the transient as soon "
  "as it is INITiated.\n"
  "AGN6K7KNI_VAL_TRIG_EXPR<1-8> - Expression1 to Expression8, Selects a "
  "user-defined expression as the trigger source.\n"
  "AGN6K7KNI_VAL_TRIG_PIN<1-7> -  PIN1 to PIN7, Selects a digital port pin "
  "configured as a trigger input.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_TRIG_SOFTWARE_TRIG\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:ARB:SOURce <source>\n"
  "\n"
  "Attribute Value: 1152006"

3 all "Arb Waveform Count" AGN6K7KNI_ATTR_ARB_WFM_COUNT ViInt32 gs
  "This channel-based attribute specifies the number of times the Arb "
  "repeats.\n"
  "\n"
  "Defined Values:\n"
  "AGN6K7KNI_VAL_ARB_COUNT_INFINITY (-1) - Infinity, repeat the Arb "
  "continuously.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_ARB_COUNT_INFINITY\n"
  "1 to 256\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_ARB_COUNT_INFINITY\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]ARB:COUNt <value>|MIN|MAX|INFinity\n"
  "\n"
  "Attribute Value: 1153010"

1 all "Measurement Attributes"
  "Attributes for configuring the measurement settings of the APS. "

2 all "Measurement Time" AGN6K7KNI_ATTR_MEASUREMENT_TIME ViReal64 gs
  "This channel-based attribute sets the measurement time in number of power "
  "line cycles. Increasing the number of power line cycles reduces the "
  "measurement noise on current and voltage measurements. \n"
  "\n"
  "The number of points in 1 NPLC depends on the line frequency.\n"
  "\n"
  "Valid Range:\n"
  "0.0003072 to 1258290000000\n"
  "\n"
  "Default Value:\n"
  "1\n"
  "\n"
  "Notes:\n"
  "(1) Changing the NPLC changes the number of points and time interval "
  "setting for N79XX A models.\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:SWEep:NPLCycles <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1154002"

2 all "Measurement Window" AGN6K7KNI_ATTR_MEASUREMENT_WINDOW ViInt32 gs attrMeasurementWindowRangeTable
  "This channel-based attribute selects the measurement window. This sets a "
  "signal conditioning function used in scalar DC measurement calculations. \n"
  "\n"
  "Neither window function alters the instantaneous voltage or current data "
  "returned in the measurement array.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_MEAS_WINDOW_HANNING - Hanning, Hanning window is a \"raised "
  "cosine\" function. It is a signal conditioning function that reduces "
  "errors in DC measurement calculations in the presence of periodic signals "
  "such as AC line ripple. This window only works up to 4883 measurement "
  "points. The instrument will revert to a rectangular window when the points "
  "exceed 4883.\n"
  "AGN6K7KNI_VAL_MEAS_WINDOW_RECT - Rectangular, returns measurement "
  "calculations with no signal conditioning.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_MEAS_WINDOW_RECT\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:WINDow[:TYPE] HANNing|RECTangular\n"
  "\n"
  "Attribute Value: 1154001"

2 all "Output Range" AGN6K7KNI_ATTR_OUTPUT_RANGE ViReal64 gs
  "This channel-based attribute selects a DC current measurement range. "
  "Units are in amperes. \n"
  "\n"
  "Valid Range:\n"
  "Without power dissipator: \n"
  "N7950A and N7970A: -10.2 to 102 A\n"
  "N7951A and N7971A: -5.1 to 51 A\n"
  "N7952A and N7972A: -2.55 to 25.5 A\n"
  "N7953A, N7973A and N7956A: -1.7 to 17 A\n"
  "N7954A, N7974A and N7957A: -1.275 to 12.75 A\n"
  "\n"
  "With power dissipator: \n"
  "N7950A and N7970A: -102 to 102 A\n"
  "N7951A and N7971A: -51 to 51 A\n"
  "N7952A and N7972A: -25.5 to 25.5 A\n"
  "N7953A, N7973A and N7956A: -17 to 17 A\n"
  "N7954A, N7974A and N7957A: -12.75 to 12.75 A\n"
  "\n"
  "Default Value:\n"
  "N7950A and N7970A: 102 A\n"
  "N7951A and N7971A: 51 A\n"
  "N7952A and N7972A: 25.5 A\n"
  "N7953A, N7973A and N7956A: 17 A\n"
  "N7954A, N7974A and N7957A: 12.75 A\n"
  "\n"
  "Notes:\n"
  "(1) The value that you enter must be the highest value that you expect to "
  "measure. The instrument selects the range with the best resolution for the "
  "value entered.\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only.\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:CURRent[:DC]:RANGe[:UPPer] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1151004"

2 all "Output Range Auto" AGN6K7KNI_ATTR_OUTPUT_RANGE_AUTO ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables seamless measurement "
  "auto ranging.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - enables seamless measurement auto ranging.\n"
  "VI_FALSE - Disables seamless measurement auto ranging.\n"
  "\n"
  "Default Value: VI_TRUE\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:CURRent[:DC]:RANGe:AUTO 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1157005"

2 all "Sweep Offset Point" AGN6K7KNI_ATTR_SWEEP_OFFSET_POINT ViInt32 gs
  "This channel-based attribute defines the offset in a data sweep for "
  "triggered measurements. Positive values represent the delay after the "
  "trigger occurs but before the samples are acquired. Negative values "
  "represent data samples taken prior to the trigger.\n"
  "\n"
  "Valid Values:\n"
  "-524287 to 2000000000\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:SWEep:OFFSet:POINts <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1154005"

2 all "Sweep Point" AGN6K7KNI_ATTR_SWEEP_POINT ViInt32 gs
  "This channel-based attribute defines the number of points in a "
  "measurement. \n"
  "\n"
  "The number of points depends on the line frequency (50 Hz or 60 Hz).\n"
  "\n"
  "Valid Values:\n"
  "1 to 524288\n"
  "\n"
  "Default Value:\n"
  "3255 (60 Hz)\n"
  "3906 (50 Hz)\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:SWEep:POINts <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1154004"

2 all "Sweep Time Interval" AGN6K7KNI_ATTR_SWEEP_TIME_INTERVAL ViReal64 gs
  "This channel-based attribute defines the time period between measurement "
  "samples.  Units are in seconds.\n"
  "\n"
  "Valid Range:\n"
  "0.00000512 to 40,000, Values are rounded to the nearest 20.48 microsecond "
  "increment. Below 20.48 microseconds, values are rounded to the nearest "
  "10.24 or 5.12 microsecond increment respectively.\n"
  "\n"
  "Default Value:\n"
  "0.00000512\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:SWEep:TINTerval <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1154003"

2 all "Acquisition Attributes"
  "Attributes for configuring the aquisition system of the APS."

3 all "Acquisition Trigger Source" AGN6K7KNI_ATTR_ACQ_TRIGGER_SOURCE ViInt32 gs attrTriggerSourceRangeTable
  "This channel-based attribute selects the trigger source for the "
  "acquisition system.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_SOFTWARE_TRIG - Software Trigger, Selects a remote interface "
  "trigger command.\n"
  "AGN6K7KNI_VAL_TRIG_CURRENT - Current Level, Selects an output current "
  "level.\n"
  "AGN6K7KNI_VAL_TRIG_EXTERNAL - External, Selects all digital port pins that "
  "have been configured as trigger sources.\n"
  "AGN6K7KNI_VAL_TRIG_EXPR<1-8> - Expression1 to Expression8, Selects a "
  "user-defined expression as the trigger source.\n"
  "AGN6K7KNI_VAL_TRIG_PIN<1-7> -  PIN1 to PIN7, Selects a digital port pin "
  "configured as a trigger input.\n"
  "AGN6K7KNI_VAL_TRIG_TRAN - Transient, Selects the transient system as the "
  "trigger source.\n"
  "AGN6K7KNI_VAL_TRIG_VOLTAGE - Voltage Level, Selects an output voltage "
  "level.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_SOFTWARE_TRIG\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:ACQuire:SOURce <source>\n"
  "\n"
  "Attribute Value: 1152007"

3 all "Acquisition Triggered Current Level" AGN6K7KNI_ATTR_ACQ_TRIGGERED_CURRENT_LEVEL ViReal64 gs
  "This channel-based attribute sets the triggered current level of the "
  "output for the acquisition system.\n"
  "\n"
  "Valid Range:\n"
  "-10.2% to 102% of rating without power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -10.2 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: -5.1 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: -2.55 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -1.7 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -1.275 to 12.75 A\n"
  "\n"
  "up to -102% to 102% of rating with power dissipator, If current rating is "
  "100%, then the valid range is: \n"
  "N6950A, N6970A, N7950A and N7970A: -102 to 102 A\n"
  "N6951A, N6971A, N7951A and N7971A: -51 to 51 A\n"
  "N6952A, N6972A, N7952A and N7972A: -25.5 to 25.5 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: -17 to 17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: -12.75 to 12.75 A\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 1.02 A\n"
  "N6951A, N6971A, N7951A and N7971A: 0.51 A\n"
  "N6952A, N6972A, N7952A and N7972A: 0.255 A\n"
  "N6953A, N6973A, N7953A, N7973A, N6976A and N7976A: 0.17 A\n"
  "N6954A, N6974A, N7954A, N7974A, N6977A and N7977A: 0.1275 A\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:ACQuire:CURRent[:LEVel] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1152005"

3 all "Acquisition Triggered Current Slope" AGN6K7KNI_ATTR_ACQ_TRIGGERED_CURRENT_SLOPE ViInt32 gs attrAcqTriggeredSlopeRangeTable
  "This channel-based attribute sets the slope of the signal.  Applies when "
  "the measurement trigger source is set to a level.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_POS - Positive, specifies a rising slope of "
  "the output signal.\n"
  "AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_NEG - Negative, specifies a falling slope of "
  "the output signal.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_POS\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:ACQuire:CURRent:SLOPe POSitive|NEGative\n"
  "\n"
  "Attribute Value: 1152003"

3 all "Acquisition Triggered Voltage Level" AGN6K7KNI_ATTR_ACQ_TRIGGERED_VOLTAGE_LEVEL ViReal64 gs
  "This channel-based attribute sets the triggered voltage level of the "
  "output for the acquisition system.\n"
  "\n"
  "Valid Range:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 to 9.18 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 to 20.4 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 to 40.8 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 to 61.2 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 to 81.6 V\n"
  "N6976A, N7976A: 0.12 to 122.4 V\n"
  "N6977A, N7977A: 0.16 to 163.2 V\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 0.009 V\n"
  "N6951A, N6971A, N7951A and N7971A: 0.02 V\n"
  "N6952A, N6972A, N7952A and N7972A: 0.04 V\n"
  "N6953A, N6973A, N7953A and N7973A: 0.06 V\n"
  "N6954A, N6974A, N7954A and N7974A: 0.08 V\n"
  "N6976A, N7976A: 0.12 V\n"
  "N6977A, N7977A: 0.16 V\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:ACQuire:VOLTage[:LEVel] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1152004"

3 all "Acquisition Triggered Voltage Slope" AGN6K7KNI_ATTR_ACQ_TRIGGERED_VOLTAGE_SLOPE ViInt32 gs attrAcqTriggeredSlopeRangeTable
  "This channel-based attribute sets the slope of the signal.  Applies when "
  "the measurement trigger source is set to a level.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_POS - Positive, specifies a rising slope of "
  "the output signal.\n"
  "AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_NEG - Negative, specifies a falling slope of "
  "the output signal.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_TRIG_ACQ_SLOPE_POS\n"
  "\n"
  "SCPI Command:\n"
  "TRIGger:ACQuire:VOLTage:SLOPe POSitive|NEGative\n"
  "\n"
  "Attribute Value: 1152002"

2 all "Datalog Attributes"
  "Attributes for configuring the external datalog settings of the APS. "

3 all "Elog Current Enabled" AGN6K7KNI_ATTR_ELOG_CURRENT_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the Elog for specified "
  "current measurement function.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables the Elog current measurement function.\n"
  "VI_FALSE - Disables the Elog current measurement function.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:FUNCtion:CURRent 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1157007"

3 all "Elog Current Range" AGN6K7KNI_ATTR_ELOG_CURRENT_RANGE ViReal64 gs
  "This channel-based attribute selects the Elog current measurement range.  "
  "\n"
  "\n"
  "Units are in amperes.  \n"
  "\n"
  "Valid Range:\n"
  "N6950A, N6970A, N7950A and N7970A: -450 to 450 A\n"
  "N6951A, N6971A, N7951A and N7971A: -225 to 225 A\n"
  "N6952A, N6972A, N7952A and N7972A: -112.5 to 112.5 A\n"
  "N6953A, N6973A, N7953A and N7973A: -74.9 to 74.9 A\n"
  "N6954A, N6974A, N7954A and N7974A: -56.2 to 56.2 A\n"
  "N6976A and N7976A: -37.6 to 37.6 A\n"
  "N6977A and N7977A: -28.1 to 28.1 A\n"
  "\n"
  "Default Value:\n"
  "N6950A, N6970A, N7950A and N7970A: 450 A\n"
  "N6951A, N6971A, N7951A and N7971A: 225 A\n"
  "N6952A, N6972A, N7952A and N7972A: 112.5 A\n"
  "N6953A, N6973A, N7953A and N7973A: 74.9 A\n"
  "N6954A, N6974A, N7954A and N7974A: 56.2 A\n"
  "N6976A and N7976A: 37.6 A\n"
  "N6977A and N7977A: 28.1 A\n"
  "\n"
  "Notes:\n"
  "(1) The value that you enter must be the highest value that you expect to "
  "measure. The instrument selects the range with the best resolution for the "
  "value entered.\n"
  "(2) This attribute supports N79XX models only.\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:CURRent[:DC]:RANGe[:UPPer] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1155001"

3 all "Elog Current Range Auto" AGN6K7KNI_ATTR_ELOG_CURRENT_RANGE_AUTO ViBoolean gs Boolean_values
  "This attribute enables or disables Elog seamless measurement autoranging.\n"
  "\n"
  "Valid values:\n"
  "VI_TRUE - Enables Elog autoranging\n"
  "VI_FALSE - Disables Elog autoranging\n"
  "\n"
  "Default Value:\n"
  "VI_TRUE\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:CURRent[:DC]:RANGe:AUTO 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1157010"

3 all "Elog Current Min/Max Enabled" AGN6K7KNI_ATTR_ELOG_CURRENT_MINMAX_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables logging of the minimum "
  "and maximum current values.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables logging.\n"
  "VI_FALSE - Disables logging.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:FUNCtion:CURRent:MINMax 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1157006"

3 all "Elog Period" AGN6K7KNI_ATTR_ELOG_PERIOD ViReal64 gs
  "This channel-based attribute sets the integration time of an Elog "
  "measurement.\n"
  "\n"
  "Valid Range:\n"
  "0.0001024 to 60\n"
  "\n"
  "Default Value:\n"
  "60\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:PERiod <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1155002"

3 all "Elog Voltage Enabled" AGN6K7KNI_ATTR_ELOG_VOLTAGE_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables the Elog for specified "
  "voltage measurement function.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables the Elog voltage measurement function.\n"
  "VI_FALSE - Disables the Elog voltage measurement function.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:FUNCtion:VOLTage 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1157009"

3 all "Elog Voltage Min/Max Enabled" AGN6K7KNI_ATTR_ELOG_VOLTAGE_MINMAX_ENABLED ViBoolean gs Boolean_values
  "This channel-based attribute enables or disables logging of the minimum "
  "and maximum voltage values.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables logging.\n"
  "VI_FALSE - Disables logging.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "Notes:\n"
  "(1) This attribute supports N79XX models only\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:ELOG:FUNCtion:VOLTage:MINMax 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1157008"

1 all "Calibration Attributes"
  "Attributes for configuring the calibration settings of the APS. "

2 all "Calibration Count" AGN6K7KNI_ATTR_CALIBRATION_COUNT ViInt32 g
  "This attribute returns the number of times the unit has been calibrated. "
  "The count is incremented whenever the calibration (and date) is saved, the "
  "administration password is changed or reset, or the firmware is updated.\n"
  "\n"
  "SCPI Command:\n"
  "CALibrate:COUNt?\n"
  "\n"
  "Attribute Value: 1157011"

2 all "Calibration Data" AGN6K7KNI_ATTR_CALIBRATION_DATA ViReal64 s
  "This attribute sets the calibration value read by the external meter. "
  "Data values are expressed in base units - either volts or amperes, "
  "depending on which function is being calibrated.\n"
  "\n"
  "Default Value: \n"
  "None\n"
  "\n"
  "SCPI Command:\n"
  "CALibrate:DATA <value>\n"
  "\n"
  "Attribute Value: 1157001"

2 all "Calibration Level" AGN6K7KNI_ATTR_CALIBRATION_LEVEL ViInt32 gs attrCalibrationLevelRangeTable
  "This attribute advances to the next level in the calibration.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_CAL_LEVEL_P1 - P1, first level\n"
  "AGN6K7KNI_VAL_CAL_LEVEL_P2 - P2, second level\n"
  "AGN6K7KNI_VAL_CAL_LEVEL_P3 - P3, third level\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_CAL_LEVEL_P1\n"
  "\n"
  "SCPI Command:\n"
  "CALibrate:LEVel P1|P2|P3\n"
  "\n"
  "Attribute Value: 1157003"

1 all "System"
  "Attributes for configuring the system settings of the APS. "

2 all "Output Off Couple Source" AGN6K7KNI_ATTR_OUTPUT_OFF_COUPLE_SOURCE ViInt32 gs attrExpressionSourceRangeTable
  "This attribute sets the off-couple signal source to an expression.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_NONE - None\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR1 - Expression1\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR2 - Expression2\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR3 - Expression3\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR4 - Expression4\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR5 - Expression5\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR6 - Expression6\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR7 - Expression7\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR8 - Expression8\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_EXPRESSTION_SOURCE_EXPR1\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:COUPle:OFF:SOURce EXPRession <1-8>\n"
  "\n"
  "Attribute Value: 1153001"

2 all "Output On Couple Source" AGN6K7KNI_ATTR_OUTPUT_ON_COUPLE_SOURCE ViInt32 gs attrExpressionSourceRangeTable
  "This attribute sets the on-couple signal source to an expression.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_NONE - None\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR1 - Expression1\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR2 - Expression2\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR3 - Expression3\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR4 - Expression4\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR5 - Expression5\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR6 - Expression6\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR7 - Expression7\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR8 - Expression8\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR1\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut[:STATe]:COUPle:ON:SOURce EXPRession <1-8>\n"
  "\n"
  "Attribute Value: 1153002"

2 all "Sense Fault Detection Enabled" AGN6K7KNI_ATTR_SENSE_FAULT_DET_ENABLED ViBoolean gs Boolean_values
  "This attribute enables or disables remote sense fault detection. This "
  "condition is annunciated by the SF status bit.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables remote sense fault detection.\n"
  "VI_FALSE - Disables remote sense fault detection.\n"
  "\n"
  "Default Value:\n"
  "VI_TRUE\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:FAULt:STATe 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1156005"

2 all "User Protection Enabled" AGN6K7KNI_ATTR_UESR_PROTECTION_ENABLED ViBoolean gs Boolean_values
  "This attribute enables or disables the user-defined protection.\n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables the user-defined protection.\n"
  "VI_FALSE - Disables the user-defined protection.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:PROTection:USER[:STATe] 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1156002"

2 all "User Protection Source" AGN6K7KNI_ATTR_USER_PROTECTION_SOURCE ViInt32 gs attrExpressionSourceRangeTable
  "This attribute sets the user-defined protection source to an expression. "
  "When an expression is specified, the output is disabled if the expression "
  "is true.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_NONE - None\n"
  "AGN6K7KNI_VAL_EXPRESSION_SOURCE_EXPR<1-8> - Expression<1-8>\n"
  "\n"
  "Default Values:\n"
  "AGN6K7KNI_VAL_USER_PROTECTION_SOURCE_NONE\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:PROTection:USER:SOURce EXPRession<1-8>|NONE\n"
  "\n"
  "Attribute Value: 1156001"

2 all "Digital Port Attributes"
  "Attributes for configuring the digital IO port settings of the APS. "

3 all "Digital Inhibit Mode" AGN6K7KNI_ATTR_DIGITAL_INHIBIT_MODE ViInt32 gs attrDigitalInhibitModeRangeTable
  "This attribute sets the operating mode of the remote inhibit digital pin. "
  "The inhibit function shuts down the output in response to an external "
  "signal on the Inhibit input pin. \n"
  "\n"
  "The Inhibit mode is stored in non-volatile memory. \n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_LATCHING - Latching, allows a true "
  "signal on digital port PIN3 when configured as Inhibit In to disable "
  "output.\n"
  "AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_LIVE - Live, allows the output to "
  "follow the state of the Inhibit In pin. When Inhibit In is true, the "
  "output is disabled. When Inhibit In is false, the output is not affected.\n"
  "AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_OFF - The Inhibit input is ignored.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_DIGITAL_INHIBIT_MODE_OFF\n"
  "\n"
  "SCPI Command:\n"
  "OUTPut:INHibit:MODE LATChing|LIVE|OFF\n"
  "\n"
  "Attribute Value: 1156006"

3 all "Digital Input Data" AGN6K7KNI_ATTR_DIGITAL_INPUT_DATA ViInt32 g
  "This attribute returns the binary-weighted value of the state of pins 1 "
  "through 7 in bits 0 through 6 respectively.\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]DIGital:INPut:DATA?\n"
  "\n"
  "Attribute Value: 1156008"

3 all "Digital Output Bus Trigger Enabled" AGN6K7KNI_ATTR_DIGITAL_OUTPUT_BUS_TRIGGER_ENABLED ViBoolean gs Boolean_values
  "This attribute enables or disables BUS triggers on digital port pins. \n"
  "\n"
  "This allows a BUS trigger to be sent to any digital port pin that has been "
  "configured as a trigger output. A trigger out pulse is generated when the "
  "state is on and a bus trigger is received. \n"
  "\n"
  "Valid Values:\n"
  "VI_TRUE - Enables BUS triggers on digital port pins.\n"
  "VI_FALSE - Disables BUS triggers on digital port pins.\n"
  "\n"
  "Default Value:\n"
  "VI_FALSE\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]DIGital:TOUTput:BUS[:ENABle] 0|OFF|1|ON\n"
  "\n"
  "Attribute Value: 1156007"

3 all "Digital Output Data" AGN6K7KNI_ATTR_DIGITAL_OUTPUT_DATA ViInt32 gs
  "This attribute sets the state of the digital control port. This only "
  "affects the pins whose function has been set to Digital IO operation.\n"
  "\n"
  "The port has seven signal pins and a digital ground pin. In the "
  "binary-weighted value that is written to the port, the pins are controlled "
  "according to the following bit assignments: \n"
  "\n"
  "Pin               1     2     3     4     5     6     7\n"
  "Bit number        0     1     2     3     4     5     6\n"
  "Decimal value     1     2     4     8     16    32    64\n"
  "\n"
  "Valid Values:\n"
  "0 to 127\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]DIGital:OUTPut:DATA <value>\n"
  "\n"
  "Attribute Value: 1156009"

3 all "Digital Pin Function" AGN6K7KNI_ATTR_DIGITAL_PIN_FUNCTION ViInt32 gs attrDigitalPinFunctionRangeTable
  "This attribute sets the function of the pins. The functions are saved in "
  "non-volatile memory.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_DIO - Digital Input/Output, General-purpose "
  "ground-referenced digital input/output function.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_DIN - Digital Input, Digital input-only "
  "mode.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_EXPR<1-7> - Expression<1-7>, A user-defined "
  "expression drives the pin.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_FAULT - Fault Output, Pin 1 functions as an "
  "isolated fault output. Pin 2 is common for pin 1\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_INHIBIT - Inhibit Input, Pin 3 functions as "
  "an inhibit input.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_ON_COUPLE - On Couple, Pins 4 -7 "
  "synchronize the output On state.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_OFF_COUPLE - Off Couple, Pins 4 -7 "
  "synchronize the output Off state.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_TRIG_INPUT - Trigger Input, A trigger input "
  "function.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_TRIG_OUTPUT - Trigger Output, A trigger "
  "output function.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_FUNC_DIN\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]DIGital:PIN<1-7>:FUNCtion <function>\n"
  "\n"
  "Attribute Value: 1156013"

3 all "Digital Pin Polarity" AGN6K7KNI_ATTR_DIGITAL_PIN_POLARITY ViInt32 gs attrDigitalPinPolarityRangeTable
  "This attribute sets the polarity of the pins.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_POL_POS - Positive, a logical true signal is a "
  "voltage high at the pin.\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_POL_NEG - Negative, a logical true signal is a "
  "voltage low at the pin.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_DIGITAL_PIN_POL_POS\n"
  "\n"
  "SCPI Command:\n"
  "[SOURce:]DIGital:PIN<1-7>:POLarity POSitive|NEGative\n"
  "\n"
  "Attribute Value: 1156012"

2 all "Threshold Comparator Attributes"
  "Attributes for configuring the threshold comparator settings of the APS. "
  ""

3 all "Threshold Function" AGN6K7KNI_ATTR_THRESHOLD_FUNCTION ViInt32 gs attrThresholdFunctionRangeTable
  "This channel-based attribute sets the sensing function for comparators "
  "THR1, THR2, THR3 or THR4.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_THRESHOLD_FUNC_AHOUR - Ampere-hour, selects the amp-hour "
  "function.\n"
  "AGN6K7KNI_VAL_THRESHOLD_FUNC_CURRENT - Current, selects the current "
  "function.\n"
  "AGN6K7KNI_VAL_THRESHOLD_FUNC_POWER - Power, selects the power function.\n"
  "AGN6K7KNI_VAL_THRESHOLD_FUNC_VOLTAGE - Voltage, selects the voltage "
  "function.\n"
  "AGN6K7KNI_VAL_THRESHOLD_FUNC_WHOUR - Watt-hour, selects the watt-hour "
  "function.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_THRESHOLD_FUNC_VOLTAGE\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:FUNCtion AHOur|CURRent|POWer|VOLTage|WHOur\n"
  "\n"
  "Attribute Value: 1156021"

3 all "Threshold Level" AGN6K7KNI_ATTR_THRESHOLD_LEVEL ViReal64 gs
  "This channel-based attribute selects the threshold level for comparators "
  "1,2,3 or 4 for the specified threshold function.\n"
  "\n"
  "Valid Range:\n"
  "Threshold Function          Range\n"
  "Ampere-hour                 0 to +2.251165E+10\n"
  "Current                     0 to +6.248237E+01\n"
  "Power                       0 to +3.130377E+03\n"
  "Voltage                     0 to +5.008797E+01\n"
  "Watt-hour                   0 to +1.127837E+12\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:AHOur[:LEVel] <value>|MIN|MAX\n"
  "SENSe:THReshold<1|2|3|4>:CURRent[:LEVel] <value>|MIN|MAX\n"
  "SENSe:THReshold<1|2|3|4>:POWer[:LEVel] <value>|MIN|MAX\n"
  "SENSe:THReshold<1|2|3|4>:VOLTage[:LEVel] <value>|MIN|MAX\n"
  "SENSe:THReshold<1|2|3|4>:WHOur[:LEVel] <value>|MIN|MAX\n"
  "\n"
  "Attribute Value: 1156019"

3 all "Threshold Operation" AGN6K7KNI_ATTR_THRESHOLD_OPERATION ViInt32 gs attrThresholdOperationRangeTable
  "This channel-based attribute sets the operation type for comparator 1,2,3 "
  "or 4.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_THRESHOLD_OPERATION_GT - Greater Than, specifies that the "
  "signal will be true if the measurement is greater than the threshold "
  "level.\n"
  "AGN6K7KNI_VAL_THRESHOLD_OPERATION_LT - Less Than, specifies that the "
  "signal will be true if the measurements less than the threshold level.\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_THRESHOLD_OPERATION_GT\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:OPERation GT|LT\n"
  "\n"
  "Attribute Value: 1156020"

1 all "Miscellaneous Attributes"
  "Additional Attributes."

2 all "ID Query Response" AGN6K7KNI_ATTR_ID_QUERY_RESPONSE ViString g
  "Returns the ID Query response string.  The instrument driver gets the "
  "value of this attribute when you pass VI_TRUE for the ID Query parameter "
  "to the agn6k7kni_init or agn6k7kni_InitWithOptions function.\n"
  "    \n"
  "\n"
  "SCPI Command:\n"
  "*IDN?\n"
  "\n"
  "Attribute Value: 1150001"

2 all "Hidden Attributes (not user-viewable)"
  "    "

3 all "Arb Waveform Type" AGN6K7KNI_ATTR_ARB_WFM_TYPE ViInt32 hidden attrArbWfmTypeRangeTable
  "Hidden attribute."

3 all "Check Status Callback" AGN6K7KNI_ATTR_CHECK_STATUS_CALLBACK ViInt32 hidden
  "This attribute is hidden.\n"
  "    "

3 all "Instrument Model" AGN6K7KNI_ATTR_INSTR_MODEL ViInt32 hidden
  "This hidden attribute stored the instrument model."

3 all "Instrument Modules Ranges" AGN6K7KNI_ATTR_INSTR_MODULES_RANGES ViAddr hidden
  "Hidden Attribute."

3 all "Instrument Option" AGN6K7KNI_ATTR_INSTR_OPTION ViInt32 hidden
  "This hidden attribute stored the installed instrument options.\n"
  "\n"
  "SCPI Command:\n"
  "*OPT?"

3 all "OPC Callback Timeout" AGN6K7KNI_ATTR_OPC_TIMEOUT ViInt32 hidden
  "This attribute is hidden.  The driver uses this attribute internally to "
  "set the timeout for the OPC callback.\n"
  "    "

3 all "OPC Callback" AGN6K7KNI_ATTR_OPC_CALLBACK ViInt32 hidden
  "This attribute is hidden.\n"
  "    "

3 all "Measurement Type" AGN6K7KNI_ATTR_MEASUREMENT_TYPE ViInt32 hidden attrMeasurementTypeRangeTable
  "Hidden Attribute"

3 all "Threshold Comparator Number" AGN6K7KNI_ATTR_THRESHOLD_COMPARATOR_NUMBER ViInt32 hidden attrThresholdComparatorNumberRangeTable
  "This hidden attribute specifies the threshold comparator number.\n"
  "\n"
  "Valid Values:\n"
  "AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_1 - Comparator1\n"
  "AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_2 - Comparator2\n"
  "AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_3 - Comparator3\n"
  "AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_4 - Comparator4\n"
  "\n"
  "Default Value:\n"
  "AGN6K7KNI_VAL_THRESHOLD_COMPARATOR_1"

3 all "Threshold Level Ampere-hour" AGN6K7KNI_ATTR_THRESHOLD_LEVEL_AHOUR ViReal64 hidden
  "This channel-based hidden attribute selects the threshold level for "
  "comparators 1,2,3 or 4 for the Ampere-hour threshold function.\n"
  "\n"
  "Valid Range:\n"
  "0 to +2.251165E+10\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:AHOur[:LEVel] <value>|MIN|MAX"

3 all "Threshold Level Current" AGN6K7KNI_ATTR_THRESHOLD_LEVEL_CURRENT ViReal64 hidden
  "This channel-based hidden attribute selects the threshold level for "
  "comparators 1,2,3 or 4 for the current threshold function.\n"
  "\n"
  "Valid Range:\n"
  "0 to +6.248237E+01\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:CURRent[:LEVel] <value>|MIN|MAX"

3 all "Threshold Level Power" AGN6K7KNI_ATTR_THRESHOLD_LEVEL_POWER ViReal64 hidden
  "This channel-based hidden attribute selects the threshold level for "
  "comparators 1,2,3 or 4 for the power threshold function.\n"
  "\n"
  "Valid Range:\n"
  "0 to +3.130377E+03\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:POWer[:LEVel] <value>|MIN|MAX"

3 all "Threshold Level Voltage" AGN6K7KNI_ATTR_THRESHOLD_LEVEL_VOLTAGE ViReal64 hidden
  "This channel-based hidden attribute selects the threshold level for "
  "comparators 1,2,3 or 4 for the voltage threshold function.\n"
  "\n"
  "Valid Range:\n"
  "0 to +5.008797E+01\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:VOLTage[:LEVel] <value>|MIN|MAX"

3 all "Threshold Level Watt-hour" AGN6K7KNI_ATTR_THRESHOLD_LEVEL_WHOUR ViReal64 hidden
  "This channel-based hidden attribute selects the threshold level for "
  "comparators 1,2,3 or 4 for the Watt-hour threshold function.\n"
  "\n"
  "Valid Range:\n"
  "0 to +1.127837E+12\n"
  "\n"
  "Default Value:\n"
  "0\n"
  "\n"
  "SCPI Command:\n"
  "SENSe:THReshold<1|2|3|4>:WHOur[:LEVel] <value>|MIN|MAX"

3 all "User Interchange Check Callback" AGN6K7KNI_ATTR_USER_INTERCHANGE_CHECK_CALLBACK ViInt32 hidden
  "This attribute is hidden.\n"
  "    "

3 all "Visa RM Session" AGN6K7KNI_ATTR_VISA_RM_SESSION ViInt32 hidden
  "This attribute is hidden.\n"
  "    "

